version: '3.7'

services:
  postgres_network:
    image: 'postgres:16-alpine3.19'
    container_name: 'postgres_network'
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - '8778:5432'

volumes:
  database_data:
